import type { Relationship } from "@/lib/schema";
export const relationships: Relationship[] = [
  {
    from: "socrates",
    to: "plato-cave",
    label: "정의와 앎을 묻는 대화에서 교육과 실재의 문제로",
    type: "확장",
  },
  {
    from: "plato-cave",
    to: "newton-laws",
    label: "겉모습을 넘어 설명을 찾기 — 서로 다른 탐구 방법",
    type: "대조",
  },
  {
    from: "newton-laws",
    to: "derivative",
    label: "속도와 가속도를 순간 변화율로 표현",
    type: "도구",
  },
  {
    from: "newton-laws",
    to: "industrial-revolution",
    label: "기계의 운동을 해석하는 이론적 도구",
    type: "도구",
  },
  {
    from: "industrial-revolution",
    to: "entropy",
    label: "열기관의 효율 문제에서 열역학으로",
    type: "배경",
  },
  {
    from: "probability",
    to: "entropy",
    label: "가능한 미시상태의 수로 거시적 경향 설명",
    type: "도구",
  },
  {
    from: "probability",
    to: "evolution",
    label: "선택과 우연에 의한 빈도 변화를 구별",
    type: "도구",
  },
  {
    from: "periodic-table",
    to: "dna",
    label: "원자의 결합 성질에서 생체 분자의 구조로",
    type: "배경",
  },
  {
    from: "dna",
    to: "evolution",
    label: "유전과 변이가 자연선택의 재료를 제공",
    type: "배경",
  },
  {
    from: "entropy",
    to: "evolution",
    label: "열린 계의 질서 형성은 제2법칙과 양립",
    type: "확장",
  },
  {
    from: "roman-empire",
    to: "french-revolution",
    label: "공화정과 시민권의 의미를 시대별로 비교",
    type: "대조",
  },
  {
    from: "french-revolution",
    to: "industrial-revolution",
    label: "정치 질서와 생산 질서가 함께 바뀐 시대",
    type: "배경",
  },
  {
    from: "joseon",
    to: "korean-war",
    label: "왕조 이후 제국·식민지·분단으로 이어진 단절과 변화",
    type: "배경",
  },
  {
    from: "joseon",
    to: "french-revolution",
    label: "18세기 말 서로 다른 정치 질서를 비교",
    type: "대조",
  },
  {
    from: "enlightenment",
    to: "french-revolution",
    label: "권위 비판과 권리의 언어가 혁명 요구의 배경이 됨",
    type: "배경",
  },
  {
    from: "empiricism",
    to: "enlightenment",
    label: "지식의 근거를 묻는 논쟁과 공개적 비판",
    type: "배경",
  },
  {
    from: "plato-cave",
    to: "empiricism",
    label: "감각과 앎의 관계를 서로 다른 관점으로 검토",
    type: "대조",
  },
  {
    from: "socrates",
    to: "empiricism",
    label: "믿음의 근거를 묻는 질문을 인식론으로 확장",
    type: "확장",
  },
  {
    from: "joseon",
    to: "hangul",
    label: "통치와 지식 사업의 맥락에서 문자 설계를 이해",
    type: "배경",
  },
  {
    from: "hangul",
    to: "enlightenment",
    label: "지식 접근을 넓히는 서로 다른 시대의 방식을 비교",
    type: "대조",
  },
  {
    from: "newton-laws",
    to: "energy",
    label: "힘과 운동에서 시작·끝 상태의 에너지 장부로",
    type: "확장",
  },
  {
    from: "energy",
    to: "entropy",
    label: "보존되는 총량과 변화의 방향을 구분",
    type: "확장",
  },
  {
    from: "periodic-table",
    to: "chemical-bond",
    label: "바깥 전자 구조로 결합 성향을 해석",
    type: "배경",
  },
  {
    from: "chemical-bond",
    to: "dna",
    label: "공유 결합과 염기 사이 상호작용으로 분자 구조 이해",
    type: "배경",
  },
  {
    from: "chemical-bond",
    to: "cell",
    label: "막과 생체 분자의 성질을 분자 수준에서 해석",
    type: "배경",
  },
  {
    from: "cell",
    to: "dna",
    label: "세포가 유전 정보를 사용해 단백질을 합성",
    type: "확장",
  },
  {
    from: "energy",
    to: "cell",
    label: "대사를 에너지 전환과 열린 계로 이해",
    type: "도구",
  },
  {
    from: "derivative",
    to: "integral",
    label: "순간 변화율과 누적을 미적분의 기본정리로 연결",
    type: "확장",
  },
  {
    from: "integral",
    to: "energy",
    label: "변하는 힘이 하는 일을 누적으로 계산",
    type: "도구",
  },
  {
    from: "integral",
    to: "probability",
    label: "연속 확률밀도의 구간 누적이 확률",
    type: "도구",
  },
];
