import type { Subject } from "@/lib/schema";
export const subjects: Subject[] = [
  {
    id: "world-history",
    title: "세계사",
    group: "역사",
    color: "var(--world-history)",
    description: "오늘의 세계는 어떻게 만들어졌을까.",
    categories: [
      "고대 문명",
      "고전 세계",
      "중세 세계",
      "근세",
      "산업화 시대",
      "근현대사",
      "현대 세계",
    ],
  },
  {
    id: "korean-history",
    title: "한국사",
    group: "역사",
    color: "var(--korean-history)",
    description: "한반도에서 이어진 변화의 흐름.",
    categories: [
      "선사 시대",
      "삼국 시대",
      "통일 신라와 발해",
      "고려",
      "조선",
      "일제 강점기",
      "해방과 한국 전쟁",
      "현대 한국",
    ],
  },
  {
    id: "philosophy",
    title: "철학",
    group: "철학",
    color: "var(--philosophy)",
    description: "당연한 것에 좋은 질문을 던지는 일.",
    categories: [
      "고대 철학",
      "중세 철학",
      "근대 철학",
      "현대 철학",
      "윤리학",
      "인식론",
      "형이상학",
      "정치철학",
      "과학철학",
    ],
  },
  {
    id: "physics",
    title: "물리학",
    group: "과학",
    color: "var(--physics)",
    description: "익숙한 현상 아래 숨어 있는 법칙.",
    categories: [
      "고전역학",
      "파동",
      "전자기학",
      "열역학",
      "상대성이론",
      "양자역학",
      "입자와 핵",
      "천체물리학",
    ],
  },
  {
    id: "chemistry",
    title: "화학",
    group: "과학",
    color: "var(--chemistry)",
    description: "물질의 성질과 변화의 언어.",
    categories: [
      "원자 구조",
      "주기율표",
      "화학 결합",
      "화학 반응",
      "열역학",
      "유기화학",
      "생화학",
    ],
  },
  {
    id: "biology",
    title: "생물학",
    group: "과학",
    color: "var(--biology)",
    description: "작은 세포에서 생명의 역사까지.",
    categories: ["세포", "유전", "진화", "인체", "미생물", "생태", "신경과학"],
  },
  {
    id: "mathematics",
    title: "수학",
    group: "수학",
    color: "var(--mathematics)",
    description: "변화와 패턴을 이해하는 도구.",
    categories: [
      "산술",
      "대수",
      "기하",
      "삼각함수",
      "미적분",
      "확률",
      "통계",
      "선형대수",
      "이산수학",
    ],
  },
];
export const subjectById = Object.fromEntries(
  subjects.map((s) => [s.id, s]),
) as Record<string, Subject>;
